### PR TITLE
added linear algebra and combinatorics topics under cpp

### PR DESCRIPTION
**Pull request by rishi-1092**

### CODE REVIEW

**Comment by rishi-1092** [comment]
hey @shahednasser , it would be great if you can review my PR and merge it, would really help for my hacktoberfest participation

**Review by shahednasser — CHANGES_REQUESTED** [review]
Great work but can you please add "Linear Algebra" and "Combinatorics" in the correct alphabetical order under "Fudamental CP algorithms"?

**Comment by rishi-1092** [comment]
yeah sure

**Comment by shahednasser** [comment]
great thank you!

**Pull request merged**
