### PR TITLE
Added few resources and badges in both files. 

### PR DESCRIPTION
**Pull request by Sheetal777**
Hey! I have added few resources and some attractive badges to both of your files. Kindly review and tell me if I should do something else. Considering merging it as well.

### CODE REVIEW

**Comment by shahednasser** [comment]
Awesome thanks! Can you also add the "PRs welcome" badge to the README?

**Comment by Sheetal777** [comment]
Yes, for sure. Doing it right away :)

**Comment by shahednasser** [comment]
Great thank you for your work!

**Comment by Sheetal777** [comment]
Thanks to you too!

**Pull request merged**
