### PR TITLE
Fix hover style link in dark mode

### LINKED ISSUE #342: Fix hover style of links in dark mode
If you hover on links in dark mode the link turns to black. It should turn to a light color (like white) on hover in dark mode

### PR DESCRIPTION
**Pull request by Mannuel25**
Fix #342 

@shahednasser, kindly check to see if I did the right thing. This is my first time working with Sass 😅

### CODE REVIEW

**Review by shahednasser — CHANGES_REQUESTED** [review]
Thank you @Mannuel25 it works great but can you add `:not(.site-title)` to `a:hover` as another CSS rule is overriding it sometimes.

**Comment by Mannuel25** [comment]
> Thank you @Mannuel25 it works great but can you add `:not(.site-title)` to `a:hover` as another CSS rule is overriding it sometimes.

Oh, okay. I got this.

**Comment by Mannuel25** [comment]
@shahednasser , I've made the adjustment. Kindly check it out.

**Comment by shahednasser** [comment]
Great thanks!

**Pull request merged**
