### PR TITLE
Add a couple of JavaScript resources

### PR DESCRIPTION
**Pull request by atapas**
- Fullstack 2021
- JavaScript Promises series

Many Thanks!

### CODE REVIEW

**Comment by shahednasser** [comment]
Thank you!

**Comment by atapas** [comment]
@shahednasser 

This is great! Thanks for accepting the PR. Very glad, indeed. Will the 'hacktoberfest-accepted' label be added to the repo later? I am just curious :)

**Comment by shahednasser** [comment]
@atapas only the `hacktoberfest` label is required to be added to the repository. The `hacktoberfest-accepted` label is optionally added to PRs, however, if the PR is merged it will count to your participation

**Comment by atapas** [comment]
> @atapas only the `hacktoberfest` label is required to be added to the repository. The `hacktoberfest-accepted` label is optionally added to PRs, however, if the PR is merged it will count to your participation

Thanks a lot for the response. I thought that label is mandatory after reading the guide.

**Pull request merged**
