### PR TITLE
adding scroll to top button

### PR DESCRIPTION
**Pull request by Safiya-B**
Hello,
I added the scroll to top functionality. I'm new to contributing so I don't know if what I did is alright but I wanted give it a go. Thank you very much.

### CODE REVIEW

**Review by shahednasser — CHANGES_REQUESTED** [review]
Hello @Safiya-B thank you for the great work! Can you just change the color of the button to match the main color of the website (without a hover effect) and reduce the box shadow a little?

**Comment by Safiya-B** [comment]
No problem, is it alright like this ? I'm not sure for the box shadow though, I modified it like that : 

`filter: drop-shadow(0 2px 3px rgba(0,0,0,0.2))`

Capture d’écran 2021-02-09 à 12 07 25

**Comment by shahednasser** [comment]
Sorry for the late reply @Safiya-B yes that looks good

**Comment by shahednasser** [comment]
Great thank you so much!

**Pull request merged**
