### PR TITLE
Added free hosting websites

### PR DESCRIPTION
**Pull request by arsheelsheikh**
added the free hosting websites to `README.md`

### CODE REVIEW

**Comment by arsheelsheikh** [comment]
@shahednasser will this work or should I create a fresh new Pull Request

**Comment by shahednasser** [comment]
I see no changes in the PR @arsheelsheikh

**Comment by arsheelsheikh** [comment]
> I see no changes in the PR @arsheelsheikh

ok

> I see no changes in the PR @arsheelsheikh

@shahednasser okay I will make a new PR

**Comment by arsheelsheikh** [comment]
new PR- https://github.com/shahednasser/awesome-resources/pull/323
@shahednasser

**Pull request closed without merging**
