### PR TITLE
Adding Angular and Vue resources

### PR DESCRIPTION
**Pull request by ThanoshanMV**
Issue #1 
I have added new Angular and Vue resources. Please take a look at it.

### CODE REVIEW

**Review by shahednasser — CHANGES_REQUESTED** [review]
That's great but can you add "Angular" and "Vue" to the Content menu? Also, please place them in the correct alphabetical order.

**Comment by ThanoshanMV** [comment]
Sure, I will do that.

**Comment by ThanoshanMV** [comment]
Hi, I added them in content menu and placed them in the correct alphabetical order.

**Comment by shahednasser** [comment]
Awesome thank you!

**Pull request merged**
